source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'mysql2', '~> 0.4'
gem 'devise', '~> 4.3'
gem 'recaptcha', '~> 4.6', require: 'recaptcha/rails'
gem 'dotenv', '~> 2.2'

gem 'httpclient', '~> 2.8'

#gems for front-end
gem 'jquery-rails', '~> 4.3'
gem 'jquery-ui-rails', '~> 6.0'
# gem 'jquery-ui-rails', '~> 6.0'
# gem 'bootstrap', '~> 4.0.0.beta2.1'
gem 'bootstrap-sass', '~> 3.3'
gem 'font-awesome-rails', '~> 4.7'

gem 'dropzonejs-rails',  '~> 0.8'

# gem 'sprockets-rails', require: 'sprockets/railtie'
# gem 'react-rails', '~> 2.2'
gem 'kaminari', '~> 1.1'
gem 'ransack', '~> 1.8'
gem 'bootstrap-kaminari-views', '~> 0.0'
# gem 'select2-rails'
# gem 'active_link_to'
# gem 'axlsx'  # excel generate
# gem 'axlsx_rails' # excel generate
# gem 'roo' # excel parsing
# gem 'momentjs-rails', '>= 2.8.1'
# gem 'bootstrap3-datetimepicker-rails', '~> 3.1.3'
# gem 'toastr-rails'
# gem 'jquery-rails'
# gem 'bootstrap-sass', '~> 3.2.0'
# gem 'twitter-bootstrap-rails', '3.2.0' # only for using.. rails g bootstrap:themed [RESOURCE_NAME]

#gems for image upload
gem 'carrierwave', '~> 1.2' #, github: 'carrierwaveuploader/carrierwave'
gem 'mini_magick', '~> 4.8'
gem 'fog-aws', '~> 1.4'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
